### ISSUE TITLE
Failed at Import Image Status

### ISSUE THREAD

**Issue by tinyvogon** [awslabs/aws-gov-cloud-import#28]
Hello, I'm trying to copy an AMI from us-west-2 to us-gov-west-1, but the task failed at Import Image Status with the following error: 
`2020-09-14T19:45:57.595Z	dcb24cb0-6d39-46a6-a22d-4c7c58075d8f	ERROR	Invoke Error	{"errorType":"Error","errorMessage":"failed","stack":["Error: failed","    at _homogeneousError (/var/runtime/CallbackContext.js:12:12)","    at postError (/var/runtime/CallbackContext.js:29:51)","    at callback (/var/runtime/CallbackContext.js:41:7)","    at /var/runtime/CallbackContext.js:104:16","    at /var/task/index.js:233:13","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}`

Prior to this, the task had run in a loop and given this alarm multiple times:
```
2020-09-14T19:45:57.595Z	dcb24cb0-6d39-46a6-a22d-4c7c58075d8f	INFO	{ MissingParameter: The request must contain the parameter ebs
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'The request must contain the parameter ebs',
  code: 'MissingParameter',
  time: 2020-09-14T19:45:57.595Z,
  requestId: 'e2d57703-588e-4e96-afeb-9694a012106d',
  statusCode: 400,
  retryable: false,
  retryDelay: 27.82115435098287 }
```

Please give me some thoughts on how to deal with this problem. The AMI has 2 ebs volumes attached to it, but I would be fine just to have the root volume transferred and work from there.

**Comment by awsjason** [comment]
Just a note, only one EBS works at a time.  Please check the readme.md.  Can't tell what the issue is, but two clues:
1. message: 'The request must contain the parameter ebs',
2. /var/task/index.js:233:13

Seems to be no EBS and I'd look at the lambda at line 233 to see what its trying to call.

**Comment by tinyvogon** [comment]
Thanks for the fast response. Line 233 of the lambda is just a "failed" call: 
```
        .catch(function(err){
            console.log(err);
            callback("failed");
```

I'm not sure why it says no EBS, the raw root volume was transferred to the gov cloud S3 bucket from what I saw. I just noticed that the bucket is not public unlike the one in commercial cloud, do you think that might have caused the error?
